name: Push to Space

on:
  push:
    branches:
      - main

concurrency: push-${{ github.sha }}

jobs:
  push:
    name: Push to Space
    runs-on: ubuntu-latest
    environment: Testing
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Push to Space
        uses: neobrains/space-deployment-github-action@v0.5
        with:
          access_token: ${{ secrets.DETA_ACCESS_TOKEN }}
          project_id: ${{ secrets.DETA_PROJECT_ID }}
          space_push: true
